enable_ssl: True
handle_cookie: True

host:
  self: go.wizos.vercel.app
  proxy: s2-us2.startpage.com

replaced_urls:
  - old: www.startpage.com
    new: s2-us2.startpage.com
  - old: s2-us2.startpage.com
    new: go.wizos.vercel.app
